/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import modelo.TOrigenSismo;
import modelo.Localizacion;
import modelo.TProvincia;
import control.Controlador;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
//import modelo.ventana;

public class Menu extends javax.swing.JFrame {
    
    
    /**
     * Creates new form Menu
     * @link  http://<host>/<directory>/<directory>/.../<name>
     */
    public Menu() {
        
        initComponents();
        //ColumnsAutoSizer.sizeColumnsToFit(tabla);
//        try {
//            tabla.setModel(elControl.cargarSismos());
//        } catch (IOException ex) {
//            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
//        }
        actualizarTabla();
    }
    
    /**
     * Actualiza la información de la tabla principal del programa 
     */
    public void actualizarTabla(){
        Controlador elControl = new Controlador();
        try {
            tabla.setModel(elControl.cargarSismos());
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollTabla = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        labeltitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        MNagregarSismo = new javax.swing.JMenu();
        MNmodificarSismo = new javax.swing.JMenu();
        MNinfoEstadistica = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Información de sismos en Costa Rica");

        tabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null, null, null, null, null, null},
                {"2", null, null, null, null, null, null, null, null, null},
                {"3", null, null, null, null, null, null, null, null, null},
                {"4", null, null, null, null, null, null, null, null, null},
                {"5", null, null, null, null, null, null, null, null, null},
                {"6", null, null, null, null, null, null, null, null, null},
                {"7", null, null, null, null, null, null, null, null, null},
                {"8", null, null, null, null, null, null, null, null, null},
                {"9", null, null, null, null, null, null, null, null, null},
                {"10", null, null, null, null, null, null, null, null, null},
                {"11", null, null, null, null, null, null, null, null, null},
                {"12", null, null, null, null, null, null, null, null, null},
                {"13", null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Hora", "Magnitud", "Profundidad", "Localización", "Origen", "Latitud", "Descripción", "Longitud", "Ver"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabla.setAutoscrolls(false);
        tabla.setGridColor(new java.awt.Color(204, 153, 0));
        tabla.setShowGrid(true);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        scrollTabla.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(7).setMinWidth(500);
            tabla.getColumnModel().getColumn(7).setPreferredWidth(500);
            tabla.getColumnModel().getColumn(7).setMaxWidth(500);
        }

        labeltitulo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        labeltitulo.setForeground(new java.awt.Color(255, 102, 0));
        labeltitulo.setText("Bienvenido");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cargar sismos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        menubar.setBackground(new java.awt.Color(255, 255, 255));
        menubar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        MNagregarSismo.setBackground(new java.awt.Color(255, 255, 255));
        MNagregarSismo.setText("Agregar Sismo");
        MNagregarSismo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNagregarSismoMouseClicked(evt);
            }
        });
        menubar.add(MNagregarSismo);

        MNmodificarSismo.setText("Modificar Sismo");
        MNmodificarSismo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNmodificarSismoMouseClicked(evt);
            }
        });
        menubar.add(MNmodificarSismo);

        MNinfoEstadistica.setText("Información Estadística");
        MNinfoEstadistica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MNinfoEstadisticaMouseClicked(evt);
            }
        });
        menubar.add(MNinfoEstadistica);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTabla)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(637, 637, 637)
                                .addComponent(jLabel1))
                            .addComponent(labeltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 624, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labeltitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(25, 25, 25)
                .addComponent(scrollTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Abre la ventana Agregar Sismo
     * @param evt: Evento de presionar el botón
     */
    private void MNagregarSismoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNagregarSismoMouseClicked
        new VtnAgregarSismo(this, true).setVisible(true);
    }//GEN-LAST:event_MNagregarSismoMouseClicked
    
    /**
     * Abre la ventana Informacion Estadística
     * @param evt: Evento de presionar el botón
     */
    private void MNinfoEstadisticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNinfoEstadisticaMouseClicked
        new VtnInfoEstadistica(this, true).setVisible(true);
    }//GEN-LAST:event_MNinfoEstadisticaMouseClicked
    
    /**
     * Actualiza la información de la tabla principal del programa
     * @param evt : Evento de presionar el botón
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Abre la ventana Modificar Sismo
     * @param evt: Evento de presionar el botón
     */
    private void MNmodificarSismoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MNmodificarSismoMouseClicked
        new VtnModificarSismo(this, true).setVisible(true);
    }//GEN-LAST:event_MNmodificarSismoMouseClicked
    
    /**
     * Despliega el mapa en el navegador
     * @param evt: Evento de presionar la celda de la tabla
     */
    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        int columna = tabla.columnAtPoint(evt.getPoint());
        int fila = tabla.rowAtPoint(evt.getPoint());
        
        if (columna == 12){
            String latitud = String.valueOf(tabla.getValueAt(fila, 10));
            String longitud = String.valueOf(tabla.getValueAt(fila, 11));
            
            Controlador control = new Controlador();
            control.mostarMapa(latitud, longitud);
        }
        
        
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MNagregarSismo;
    private javax.swing.JMenu MNinfoEstadistica;
    private javax.swing.JMenu MNmodificarSismo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labeltitulo;
    public javax.swing.JMenuBar menubar;
    private javax.swing.JScrollPane scrollTabla;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    
}
