/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import control.Controlador;
import control.RegistroDeSismos;
import control.rutaGlobal;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.TOrigenSismo;
import modelo.Localizacion;
import modelo.TProvincia;
import modelo.Sismo;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;

/**
 *
 * @author andre
 */
public class VtnAgregarSismo extends javax.swing.JDialog {
    
    private Controlador elControl = new Controlador();

    /**
     * Creates new form ventana1AgregarSismo
     */
    public VtnAgregarSismo(java.awt.Frame parent, boolean modal) {    
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        
        enumOrigen.addItem("SUBDUCCION");
        enumOrigen.addItem("CHOQUE_DE_PLACAS");
        enumOrigen.addItem("TECTONICO_POR_FALLA_LOCAL");
        enumOrigen.addItem("INTRAPLACA");
        enumOrigen.addItem("DEFORMACION_INTERNA");
        
        enumLocalizacion.addItem("TERRESTRE");
        enumLocalizacion.addItem("MARITIMA");
        
        enumProvincias.addItem("SIN_ASIGNAR");
        enumProvincias.addItem("SAN_JOSE");
        enumProvincias.addItem("GUANACASTE");
        enumProvincias.addItem("PUNTARENAS");
        enumProvincias.addItem("LIMON");
        enumProvincias.addItem("ALAJUELA");
        enumProvincias.addItem("HEREDIA");
        enumProvincias.addItem("CARTAGO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelfecha = new javax.swing.JLabel();
        labelinstante = new javax.swing.JLabel();
        labelprofundidad = new javax.swing.JLabel();
        labelorigen = new javax.swing.JLabel();
        enumOrigen = new javax.swing.JComboBox<>();
        labelmagnitud = new javax.swing.JLabel();
        labellocalizacion = new javax.swing.JLabel();
        labellatitud = new javax.swing.JLabel();
        labelzona = new javax.swing.JLabel();
        labellongitud = new javax.swing.JLabel();
        enumProvincias = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        txtprofundidad = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        enumLocalizacion = new javax.swing.JComboBox<>();
        txtlatitud = new javax.swing.JTextField();
        txtlongitud = new javax.swing.JTextField();
        labelzona1 = new javax.swing.JLabel();
        txtmagnitud = new javax.swing.JTextField();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbAño = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbHora = new javax.swing.JComboBox<>();
        cbMinutos = new javax.swing.JComboBox<>();
        cbSegundos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Sismo");
        setBackground(new java.awt.Color(153, 153, 255));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 153, 153));
        labelTitulo.setText("Agregar Sismo");

        labelfecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelfecha.setText("Fecha : ");

        labelinstante.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelinstante.setText("Instante : ");

        labelprofundidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelprofundidad.setText("Profundidad (Km) : ");

        labelorigen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelorigen.setText("Origen de la falla :");

        enumOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enumOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enumOrigenActionPerformed(evt);
            }
        });

        labelmagnitud.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelmagnitud.setText("Magnitud :");

        labellocalizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labellocalizacion.setText("Localización :");

        labellatitud.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labellatitud.setText("Latitud :");

        labelzona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelzona.setText("Zona de epicentro (provincia) : ");

        labellongitud.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labellongitud.setText("Longitud :");

        enumProvincias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAgregar.setBackground(new java.awt.Color(0, 102, 51));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtprofundidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtprofundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprofundidadActionPerformed(evt);
            }
        });

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });

        enumLocalizacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtlatitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtlongitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        labelzona1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelzona1.setText("Descripción: ");

        txtmagnitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero ", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto ", "Septiembre", "Octubre ", "Noviembre ", "Diciembre " }));

        cbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));

        jLabel1.setText("Día");

        jLabel2.setText("Mes");

        jLabel3.setText("Año");

        cbHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cbMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        cbSegundos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel4.setText("Hora");

        jLabel5.setText("Minutos");

        jLabel6.setText("Segundos");

        labelId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelId.setText("Id:");

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnAgregar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelzona1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelfecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelinstante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(cbSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)))
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labellatitud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtlatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labellongitud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtlongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelprofundidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprofundidad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelmagnitud)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtmagnitud, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelorigen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enumOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labellocalizacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enumLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelzona)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enumProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelfecha)
                    .addComponent(labelinstante)
                    .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelzona)
                    .addComponent(enumProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labellocalizacion)
                    .addComponent(enumLocalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelorigen)
                    .addComponent(enumOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelprofundidad)
                    .addComponent(txtprofundidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelmagnitud)
                    .addComponent(txtmagnitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labellatitud)
                    .addComponent(txtlatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labellongitud)
                    .addComponent(txtlongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelzona1))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enumOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enumOrigenActionPerformed
        
    }//GEN-LAST:event_enumOrigenActionPerformed
    
    /**
     * Agrega un nuevo sismo
     * @param evt: Evento de presionar el botón
     */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String f = (String)cbDia.getSelectedItem() +"/"+ (cbMes.getSelectedIndex() + 1) +"/"+ cbAño.getSelectedItem();
        Date fecha = elControl.formatoFecha(f);
        String hora = (String)cbHora.getSelectedItem() +":"+ cbMinutos.getSelectedItem() +":"+ cbSegundos.getSelectedItem();
        String o = enumOrigen.getSelectedItem().toString();
        TOrigenSismo origen = TOrigenSismo.valueOf(o);
        String l = enumLocalizacion.getSelectedItem().toString();
        Localizacion localizacion = Localizacion.valueOf(l);
        String e = enumProvincias.getSelectedItem().toString();
        TProvincia epicentro = TProvincia.valueOf(e);
        String descripcion = txtDescripcion.getText();
        
        if (elControl.esNumero(txtmagnitud.getText()) && elControl.esNumero(txtprofundidad.getText()) &&
             elControl.esNumero(txtlatitud.getText()) && elControl.esNumero(txtlongitud.getText()) &&
                elControl.esNumero(txtId.getText()) && ! descripcion.isEmpty()){
            double magnitud = Double.parseDouble(txtmagnitud.getText());
            double profundidad = Double.parseDouble(txtprofundidad.getText());
            double latitud = Double.parseDouble(txtlatitud.getText());
            double longitud = Double.parseDouble(txtlongitud.getText());
            int id = Integer.parseInt(txtId.getText());
            
            if(magnitud > 0 && profundidad >= 0 && latitud >= 0 && longitud <= 0){
                
                if(elControl.agregarSismo(fecha,hora,profundidad,origen,magnitud,localizacion,latitud,longitud, 
                                  descripcion,epicentro,id)){
                    Menu elMenu = new Menu();
                    elMenu.actualizarTabla();
                    JOptionPane.showMessageDialog(null, "Sismo agregado correctamente");
                    dispose();
                }else
                JOptionPane.showMessageDialog(null, "Sismo repetido. No se puede agregar");
            }else
                JOptionPane.showMessageDialog(null, "Magnitud, profundidad y latitud deben ser números positivos.\n"
                        + "\tLongitud debe ser un número negativo");
        
        }else
            JOptionPane.showMessageDialog(null, "Sismo no agregado. Debe indicar los campos correctamente");
 
        
        
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtprofundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprofundidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprofundidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAgregarSismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAgregarSismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAgregarSismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAgregarSismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VtnAgregarSismo dialog = new VtnAgregarSismo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbAño;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbHora;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbMinutos;
    private javax.swing.JComboBox<String> cbSegundos;
    private javax.swing.JComboBox<String> enumLocalizacion;
    private javax.swing.JComboBox<String> enumOrigen;
    private javax.swing.JComboBox<String> enumProvincias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelfecha;
    private javax.swing.JLabel labelinstante;
    private javax.swing.JLabel labellatitud;
    private javax.swing.JLabel labellocalizacion;
    private javax.swing.JLabel labellongitud;
    private javax.swing.JLabel labelmagnitud;
    private javax.swing.JLabel labelorigen;
    private javax.swing.JLabel labelprofundidad;
    private javax.swing.JLabel labelzona;
    private javax.swing.JLabel labelzona1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtlatitud;
    private javax.swing.JTextField txtlongitud;
    private javax.swing.JTextField txtmagnitud;
    private javax.swing.JTextField txtprofundidad;
    // End of variables declaration//GEN-END:variables
}
