/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.CargadorGraficos;
import control.Controlador;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author andre
 */
public class VtnInfoEstadistica extends javax.swing.JDialog {
    
    CargadorGraficos cargador = new CargadorGraficos();
    Controlador control = new Controlador();
    
    /**
     * Creates new form VtnInfoEstadistica
     */
    public VtnInfoEstadistica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargador.llamarAlExcel();
        deshabiliarCB();
        try {
            cbAños.setModel(control.cargarAños());
        } catch (IOException ex) {
            Logger.getLogger(VtnInfoEstadistica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Deshabilita el combo box 
     */
    public void deshabiliarCB(){
       cbAños.setEnabled(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSismoPorProvincia = new javax.swing.JButton();
        btnSismosPorOrigen = new javax.swing.JButton();
        btnSismosPorMagnitud = new javax.swing.JButton();
        btnSismosPorMes = new javax.swing.JButton();
        btnSismosPorFechas = new javax.swing.JButton();
        pnlGrafico = new javax.swing.JPanel();
        cbAños = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 255));
        jLabel1.setText("Análisis de información de los sismos registrados");

        btnSismoPorProvincia.setBackground(new java.awt.Color(51, 153, 255));
        btnSismoPorProvincia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSismoPorProvincia.setText("Cantidad de sismos por provincia");
        btnSismoPorProvincia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSismoPorProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSismoPorProvinciaActionPerformed(evt);
            }
        });

        btnSismosPorOrigen.setBackground(new java.awt.Color(51, 255, 51));
        btnSismosPorOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSismosPorOrigen.setText("Cantidad de sismos por tipo de origen");
        btnSismosPorOrigen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSismosPorOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSismosPorOrigenActionPerformed(evt);
            }
        });

        btnSismosPorMagnitud.setBackground(new java.awt.Color(255, 102, 102));
        btnSismosPorMagnitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSismosPorMagnitud.setText("Clasificación de sismos por magnitud");
        btnSismosPorMagnitud.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSismosPorMagnitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSismosPorMagnitudActionPerformed(evt);
            }
        });

        btnSismosPorMes.setBackground(new java.awt.Color(153, 153, 255));
        btnSismosPorMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSismosPorMes.setText("Cantidad de sismos por mes en un año");
        btnSismosPorMes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSismosPorMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSismosPorMesActionPerformed(evt);
            }
        });

        btnSismosPorFechas.setBackground(new java.awt.Color(255, 153, 51));
        btnSismosPorFechas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSismosPorFechas.setText("Sismos ocurridos por un rango de fechas");
        btnSismosPorFechas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSismosPorFechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSismosPorFechasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGraficoLayout = new javax.swing.GroupLayout(pnlGrafico);
        pnlGrafico.setLayout(pnlGraficoLayout);
        pnlGraficoLayout.setHorizontalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        pnlGraficoLayout.setVerticalGroup(
            pnlGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        cbAños.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAñosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSismosPorMes, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSismosPorMagnitud, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSismosPorOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSismoPorProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSismosPorFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(pnlGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnSismoPorProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnSismosPorOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnSismosPorMagnitud, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnSismosPorMes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbAños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btnSismosPorFechas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Coloca el panel cargado antes en el panel de la ventana
     * @param panel: Dato tipo ChartPanel
     */
    public void setPanel(ChartPanel panel){        
        pnlGrafico.removeAll();
        pnlGrafico.setLayout(new BorderLayout());
        pnlGrafico.add(panel, BorderLayout.NORTH);

        pack();
        repaint();
    }
    
    /**
     * Muestra el gráfico de sismos por provincia
     * @param evt: Evento de presionar el botón
     */
    private void btnSismoPorProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSismoPorProvinciaActionPerformed

        try {
           setPanel(cargador.graficoSismosProvincia());
        } catch (IOException ex) {
            Logger.getLogger(VtnInfoEstadistica.class.getName()).log(Level.SEVERE, null, ex);
        }
        deshabiliarCB();
    }//GEN-LAST:event_btnSismoPorProvinciaActionPerformed

    /**
     * Muestra el gráfico de sismos por tipo de origen
     * @param evt: Evento de presionar el botón
     */
    private void btnSismosPorOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSismosPorOrigenActionPerformed
        try {
           setPanel(cargador.graficoPorOrigen());
        } catch (IOException ex) {
            Logger.getLogger(VtnInfoEstadistica.class.getName()).log(Level.SEVERE, null, ex);
        }
        deshabiliarCB();

    }//GEN-LAST:event_btnSismosPorOrigenActionPerformed

    /**
     * Muestra la ventana de sismos por tipo de Magnitud
     * @param evt: Evento de presionar el botón
     */
    private void btnSismosPorMagnitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSismosPorMagnitudActionPerformed
        deshabiliarCB();
        new VtnGraficaMagnitud(this, true).setVisible(true);
    }//GEN-LAST:event_btnSismosPorMagnitudActionPerformed
    
    /**
     * Habilita el combo box de años
     * @param evt: Evento de presionar el botón
     */
    private void btnSismosPorMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSismosPorMesActionPerformed
        cbAños.setEnabled(true);

    }//GEN-LAST:event_btnSismosPorMesActionPerformed

    /**
     * Muestra la ventana del gráfico de la cantidad de sismos por fechas
     * @param evt: Evento de presionar el botón
     */
    private void btnSismosPorFechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSismosPorFechasActionPerformed
        deshabiliarCB();
        new VtnGraficaFechas(this, true).setVisible(true);
    }//GEN-LAST:event_btnSismosPorFechasActionPerformed

    /**
     * Muestra el gráfico de cantidad de sismos por mes según el año
     * @param evt: Evento de presionar el botón
     */
    private void cbAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAñosActionPerformed
        // TODO add your handling code here:
        int año = (int)cbAños.getSelectedItem();
        try {
           setPanel(cargador.graficoMeses(año - 1900));
        } catch (IOException ex) {
            Logger.getLogger(VtnInfoEstadistica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbAñosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnInfoEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnInfoEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnInfoEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnInfoEstadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VtnInfoEstadistica dialog = new VtnInfoEstadistica(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSismoPorProvincia;
    private javax.swing.JButton btnSismosPorFechas;
    private javax.swing.JButton btnSismosPorMagnitud;
    private javax.swing.JButton btnSismosPorMes;
    private javax.swing.JButton btnSismosPorOrigen;
    private javax.swing.JComboBox<String> cbAños;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel pnlGrafico;
    // End of variables declaration//GEN-END:variables
}
