/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import control.Controlador;
import control.RegistroDeSismos;
import control.rutaGlobal;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.TProvincia;


/**
 *
 * @author andre
 */
public class VtnModificarSismo extends javax.swing.JDialog {
    
    private Controlador elControl = new Controlador();

    /**
     * Creates new form ventana1AgregarSismo
     */
    public VtnModificarSismo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        enumProvincias.addItem("SIN_ASIGNAR");
        enumProvincias.addItem("SAN_JOSE");
        enumProvincias.addItem("GUANACASTE");
        enumProvincias.addItem("PUNTARENAS");
        enumProvincias.addItem("LIMON");
        enumProvincias.addItem("ALAJUELA");
        enumProvincias.addItem("HEREDIA");
        enumProvincias.addItem("CARTAGO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgModificar = new javax.swing.ButtonGroup();
        labelTitulo = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        labelzona = new javax.swing.JLabel();
        enumProvincias = new javax.swing.JComboBox<>();
        btnModificar = new javax.swing.JButton();
        rbCoordenadas = new javax.swing.JRadioButton();
        rbEpicentro = new javax.swing.JRadioButton();
        labellatitud1 = new javax.swing.JLabel();
        txtNuevaLatitud = new javax.swing.JTextField();
        labellongitud1 = new javax.swing.JLabel();
        txtNuevaLongitud = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Sismo");
        setBackground(java.awt.SystemColor.activeCaption);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 153, 153));
        labelTitulo.setText("Modificar Sismo");

        labelId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelId.setText("Id del sismo a modificar:");

        labelzona.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labelzona.setText("Nueva zona de epicentro (provincia) : ");

        enumProvincias.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        btnModificar.setBackground(new java.awt.Color(0, 102, 51));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        bgModificar.add(rbCoordenadas);
        rbCoordenadas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rbCoordenadas.setText("Modificar Latitud y Longitud");
        rbCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCoordenadasActionPerformed(evt);
            }
        });

        bgModificar.add(rbEpicentro);
        rbEpicentro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rbEpicentro.setText("Modificar Provincia");

        labellatitud1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labellatitud1.setText("Nueva Latitud ");

        txtNuevaLatitud.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        labellongitud1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        labellongitud1.setText("Nueva longitud :");

        txtNuevaLongitud.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbEpicentro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelzona)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enumProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelId)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labellatitud1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNuevaLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labellongitud1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNuevaLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbCoordenadas))
                        .addContainerGap(199, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModificar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(21, 21, 21)
                .addComponent(labelId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(rbCoordenadas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labellatitud1)
                    .addComponent(txtNuevaLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labellongitud1)
                    .addComponent(txtNuevaLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(rbEpicentro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelzona)
                    .addComponent(enumProvincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Modifica un sismo existente
     * @param evt: Evento de presionar el botón
     */
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

          String idString = txtId.getText();
          String idResultado = idString.replaceAll("\\s+","");
          
 
        String e = enumProvincias.getSelectedItem().toString();
        TProvincia nuevoEpicentro = TProvincia.valueOf(e);
        
        if(elControl.esNumero(idResultado)){
            int id = Integer.parseInt(txtId.getText());
            if (rbCoordenadas.isSelected() && elControl.esNumero(txtNuevaLatitud.getText()) 
                    && elControl.esNumero(txtNuevaLongitud.getText())) {
            double nuevaLatitud = Double.parseDouble(txtNuevaLatitud.getText());
            double nuevaLongitud = Double.parseDouble(txtNuevaLongitud.getText());
                if(nuevaLatitud >= 0 && nuevaLongitud <= 0 && elControl.modificarSismo(id, nuevaLatitud, nuevaLongitud)){
                    JOptionPane.showMessageDialog(null, "Latitud y longitud modificadas");
                    dispose();
                }else
                    JOptionPane.showMessageDialog(null, "LATITUD debe ser positiva y LONGITUD negativa ");
            }else if(rbEpicentro.isSelected() && elControl.modificarSismo(id, nuevoEpicentro)) {
                JOptionPane.showMessageDialog(null, "Epicentro modificado");
                dispose();   
            }else
                JOptionPane.showMessageDialog(null, "Seleccione una opción válida.");        
    }else
        JOptionPane.showMessageDialog(null, "El id debe ser un número disponible");
               

    }//GEN-LAST:event_btnModificarActionPerformed

    private void rbCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCoordenadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCoordenadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAgregarSismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAgregarSismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAgregarSismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAgregarSismo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VtnModificarSismo dialog = new VtnModificarSismo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgModificar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> enumProvincias;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labellatitud1;
    private javax.swing.JLabel labellongitud1;
    private javax.swing.JLabel labelzona;
    private javax.swing.JRadioButton rbCoordenadas;
    private javax.swing.JRadioButton rbEpicentro;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNuevaLatitud;
    private javax.swing.JTextField txtNuevaLongitud;
    // End of variables declaration//GEN-END:variables
}
